version: "3.9"

networks:
  app-network:
    driver: bridge

services:

  web:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server1
      - server2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    #   - /home/ubuntu/frontend:/usr/share/nginx/html
    #   - /home/ubuntu/images:/usr/share/nginx/html/img
    networks:
      - app-network
  
  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile

    container_name: server1
    ports:
      - 8080:8080
    networks:
          - app-network
  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile

    container_name: server2
    ports:
      - 8081:8080
    networks:
      - app-network

