version: "3.9"
services:
  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile

    container_name: server1
    ports:
      - 8080:8080

  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile

    container_name: server2
    ports:
      - 8081:8080

