version: "3.9"
services:

  web:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server1
      - server2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #   - /home/ubuntu/frontend:/usr/share/nginx/html
    #   - /home/ubuntu/images:/usr/share/nginx/html/img

  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile

    container_name: server1
    ports:
      - 8080:8080

  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile

    container_name: server2
    ports:
      - 8081:8080

